# Generated by Django 2.2.9 on 2020-01-27 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('voice_type', models.CharField(max_length=100, null=True)),
                ('voice_name', models.CharField(max_length=100, null=True)),
                ('device_profile', models.CharField(max_length=100, null=True)),
                ('speed', models.FloatField(null=True)),
                ('pitch', models.FloatField(null=True)),
                ('audio', models.FileField(upload_to='audios/%Y/%m/%d/')),
                ('source', models.FileField(upload_to='images/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
