# Generated by Django 2.2.9 on 2020-01-27 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('texttospeech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='device_profile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='pitch',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='voice_name',
            field=models.CharField(max_length=100),
        ),
    ]
